### ISSUE TITLE
set `KLD_PUBLIC_ADDRESS` using IP from kld.toml

### ISSUE THREAD

**Issue by paulmattei** [kuutamolabs/lightning-knd#318]

**Comment by paulmattei** [comment]
@JosephGoulden please add more context if needed

**Comment by yanganto** [comment]
Do we need more than one public address?
`kneard` use one, and `kld` use multiple but it seems not really in use.

**Comment by yanganto** [comment]
There is `IpAddr` in the standard library, which already covers IPV4 and IPV6.  We will not validate the input format by ourselves with this type.
https://doc.rust-lang.org/std/net/enum.IpAddr.html

Could we consider refactoring this with the standard type?
https://github.com/kuutamolabs/lightning-knd/blob/0feea2f4432ffc2c83231de728d8e5dc6b895e40/api/src/lib.rs#L88-L95

**Comment by yanganto** [comment]
It is good to make a direct warper struct of `lightning::ln::msgs::NetAddress` and implement `Serialize`, `Deserialize`, and `Display` for it, such that we can manipulate the toml config directly with this struct.

We can remove the following after the warper struct
https://github.com/kuutamolabs/lightning-knd/blob/0feea2f4432ffc2c83231de728d8e5dc6b895e40/kld/src/api/network.rs#L182-L215
https://github.com/kuutamolabs/lightning-knd/blob/0feea2f4432ffc2c83231de728d8e5dc6b895e40/kld/src/ldk/net_utils.rs#L11-L30
https://github.com/kuutamolabs/lightning-knd/blob/0feea2f4432ffc2c83231de728d8e5dc6b895e40/api/src/lib.rs#L89-L94

And avoid unwrapping when changing types
https://github.com/kuutamolabs/lightning-knd/blob/0feea2f4432ffc2c83231de728d8e5dc6b895e40/kld/src/ldk/peer_manager.rs#L33

**Comment by paulmattei** [comment]
> Do we need more than one public address?

Yes I think so as we may have v4 and v6 ...

**Comment by JosephGoulden** [comment]
The protocol allows for an array of addresses so we should enable that.
Yes you can start KLD without and public addresses, you would not be able to accept incoming connections but you could still make outgoing connections.
As you can see PeerAddress is a wrapper for NetAddress. It is a bit a bit messy yes but I think refactoring this is out of scope for this issue. I'm not sure how mgr would be able to make use of this new type as there is no shared lib. Where would it go?

**Comment by yanganto** [comment]
It may be too early to say something here, and the upstream type indeed lacks utilities, such that our repo easily run into trouble.  Please give me another day, I will make it clear, then you can easily review what I mentioned.

**Comment by yanganto** [comment]
Hi @JosephGoulden, @paulmattei 

It will be refactored at the same time when something related to the field of config.  As you can see in #354, the [fe20c75](https://github.com/kuutamolabs/lightning-knd/pull/354/commits/fe20c75c99ebc7bb412c7a7dbedbdb14d32e4f64) is an implement serializer, deserializer, and other traits to the NetAdress pass all test and works well.

Topics we need to sync up the first list down here

- The inputs of corresponding will have validation, avoid using `String` and use type in the standard library to validate, so we do not need to validate by ourselves.
https://github.com/kuutamolabs/lightning-knd/blob/fe20c75c99ebc7bb412c7a7dbedbdb14d32e4f64/settings/src/lib.rs#L49-L53
- Convert to NetAddress immediately after config load, because `NetAddress` is a native type for lightning projects
https://github.com/kuutamolabs/lightning-knd/blob/fe20c75c99ebc7bb412c7a7dbedbdb14d32e4f64/settings/src/lib.rs#L82-L91
- Remove all intermediate NetAdress types (`Address`, `PeerAddress`), such that we do not need to transform between types, and also avoid some unwarps like this.
https://github.com/kuutamolabs/lightning-knd/blob/4dbeed74b0b319642842252ae8a7406ea07b8f5b/kld/src/ldk/peer_manager.rs#L33

**Comment by yanganto** [comment]
Strong typing really makes the system robust.  I know this will be an issue do it now or never, so I try to make it quick and sound.

Also, it is not really far, actually, it is almost there with all tests passed.
None of the business logic or condition change, and the types become slim. So there is nothing new actually.

We can take a look at it for now. And others will do after this, or based on it.
